In [2]:
import pandas as pd
import pymysql
import requests
import datetime

In [18]:
conn = pymysql.connect(
    host = 'localhost',
    user = 'root',
    password = 'root',
    database = 'cricbuzzdb'
)
cursor = conn.cursor()

print("connected Successfully")

connected Successfully

In [4]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS matches_info (
    match_id INT PRIMARY KEY,
    series_id INT,
    series_name VARCHAR(255),
    match_desc VARCHAR(255),
    match_format VARCHAR(50),
    start_date DATETIME,
    state varchar(20),
    status VARCHAR(255),
    team1 VARCHAR(100),
    team2 VARCHAR(100),
    venue VARCHAR(255),
    city VARCHAR(100)
)
""")

0

In [5]:
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/matches/v1/live"

headers = {
	"x-rapidapi-key": "07bd567654mshaf5d130ac122921p1c96cajsne9916179c774",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

data_1 = response.json()


#insertion into the table


count = 0
for match_type in data_1.get("typeMatches", []):
    for series in match_type.get("seriesMatches", []):
        series_data = series.get("seriesAdWrapper", {})
        series_id = series_data.get("seriesId")
        series_name = series_data.get("seriesName")

        for match in series_data.get("matches", []):
            info = match.get("matchInfo", {})
            match_id = info.get("matchId")
            match_desc = info.get("matchDesc")
            match_format = info.get("matchFormat")
            start_date = info.get("startDate")
            state = info.get("state")
            status = info.get("status")
            team1 = info.get("team1", {}).get("teamName")
            team2 = info.get("team2", {}).get("teamName")
            venue = info.get("venueInfo", {}).get("ground")
            city = info.get("venueInfo", {}).get("city")


            start_date = datetime.datetime.fromtimestamp(int(start_date) / 1000) if start_date else None

            # Insert into MySQL
            cursor.execute("""
    INSERT INTO matches_info (
        match_id, series_id, series_name, match_desc, match_format, start_date, state, status, team1, team2, venue, city
    ) VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
    ON DUPLICATE KEY UPDATE
        series_id=VALUES(series_id),
        series_name=VALUES(series_name),
        match_desc=VALUES(match_desc),
        match_format=VALUES(match_format),
        start_date=VALUES(start_date),
        state=VALUES(state),
        status=VALUES(status),
        team1=VALUES(team1),
        team2=VALUES(team2),
        venue=VALUES(venue),
        city=VALUES(city)
""", (match_id, series_id, series_name, match_desc, match_format, start_date, state, status, team1, team2, venue, city))
            
    count += 1        


            

conn.commit()
print(count)

0

In [6]:
cursor.execute("""create table if not exists matches_upcoming(match_id INT PRIMARY KEY,
    series_id INT,
    series_name VARCHAR(255),
    match_desc VARCHAR(255),
    match_format VARCHAR(50),
    start_date DATETIME,
    status VARCHAR(255),
    team1 VARCHAR(100),
    team2 VARCHAR(100),
    venue VARCHAR(255),
    city VARCHAR(100))""")

0

In [7]:
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/matches/v1/upcoming"

headers = {
	"x-rapidapi-key": "07bd567654mshaf5d130ac122921p1c96cajsne9916179c774",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

data_2 = response.json()
data_2


#insertion

count = 0
for match_type in data_2.get("typeMatches", []):
    for series in match_type.get("seriesMatches", []):
        series_data = series.get("seriesAdWrapper", {})
        series_id = series_data.get("seriesId")
        series_name = series_data.get("seriesName")

        for match in series_data.get("matches", []):
            info = match.get("matchInfo", {})
            match_id = info.get("matchId")
            match_desc = info.get("matchDesc")
            match_format = info.get("matchFormat")
            start_date = info.get("startDate")
            status = info.get("status")
            team1 = info.get("team1", {}).get("teamName")
            team2 = info.get("team2", {}).get("teamName")
            venue = info.get("venueInfo", {}).get("ground")
            city = info.get("venueInfo", {}).get("city")

            start_date = datetime.datetime.fromtimestamp(int(start_date) / 1000) if start_date else None

            # Insert into MySQL
            cursor.execute("""
                INSERT INTO matches_upcoming (match_id, series_id, series_name, match_desc, match_format, start_date, status, team1, team2, venue, city)
                VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
                ON DUPLICATE KEY UPDATE
                series_id=VALUES(series_id),
                series_name=VALUES(series_name),
                match_desc=VALUES(match_desc),
                match_format=VALUES(match_format),
                start_date=VALUES(start_date),
                status=VALUES(status),
                team1=VALUES(team1),
                team2=VALUES(team2),
                venue=VALUES(venue),
                city=VALUES(city)
            """, (match_id, series_id, series_name, match_desc, match_format, start_date, status, team1, team2, venue, city))

            count += 1

conn.commit()
print(f"{count} upcoming match records inserted/updated.")

0 upcoming match records inserted/updated.

In [ ]:
cursor.execute("""create table if not exists matches_recent(
match_id INT PRIMARY KEY,
    series_id INT,
    series_name VARCHAR(255),
    match_desc VARCHAR(255),
    match_format VARCHAR(50),
    start_date DATETIME,
    status VARCHAR(255),
    team1 VARCHAR(100),
    team2 VARCHAR(100),
    venue VARCHAR(255),
    city VARCHAR(100))""")

0

In [ ]:
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/matches/v1/recent"

headers = {
	"x-rapidapi-key": "07bd567654mshaf5d130ac122921p1c96cajsne9916179c774",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

data_3 = response.json()

data_3

#insertion


count = 0
for match_type in data_3.get("typeMatches", []):
    for series in match_type.get("seriesMatches", []):
        series_data = series.get("seriesAdWrapper", {})
        series_id = series_data.get("seriesId")
        series_name = series_data.get("seriesName")

        for match in series_data.get("matches", []):
            info = match.get("matchInfo", {})
            match_id = info.get("matchId")
            match_desc = info.get("matchDesc")
            match_format = info.get("matchFormat")
            state = info.get("state")
            start_date = info.get("startDate")
            status = info.get("status")
            team1 = info.get("team1", {}).get("teamName")
            team2 = info.get("team2", {}).get("teamName")
            venue = info.get("venueInfo", {}).get("ground")
            city = info.get("venueInfo", {}).get("city")

            start_date = datetime.datetime.fromtimestamp(int(start_date) / 1000) if start_date else None

            # Insert into MySQL
            cursor.execute("""
                INSERT INTO matches_recent (match_id, series_id, series_name, match_desc, match_format, start_date, status, team1, team2, venue, city)
                VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
                ON DUPLICATE KEY UPDATE
                series_id=VALUES(series_id),
                series_name=VALUES(series_name),
                match_desc=VALUES(match_desc),
                match_format=VALUES(match_format),
                start_date=VALUES(start_date),
                status=VALUES(status),
                team1=VALUES(team1),
                team2=VALUES(team2),
                venue=VALUES(venue),
                city=VALUES(city)
            """, (match_id, series_id, series_name, match_desc, match_format, start_date, status, team1, team2, venue, city))

            count += 1

conn.commit()
print(f"{count} recent match records inserted/updated.")

0 recent match records inserted/updated.

In [10]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS venues (
    venue_id INT PRIMARY KEY,
    venue_name VARCHAR(255),
    city VARCHAR(255),
    country VARCHAR(255),
    capacity VARCHAR(50)
)
""")

0

In [11]:
import requests

def extract_venue_details_insert(venue_ids):
    count = 0
    for vid in venue_ids:
        url = f"https://cricbuzz-cricket.p.rapidapi.com/venues/v1/{vid}"
        headers = {
            "x-rapidapi-key": "fa8e2f141fmsh93e60c107630b1ep15131djsnd985ef01f9ec ",
            "x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
        }

        try:
            response = requests.get(url, headers=headers)
            data = response.json()
        except Exception as e:
            print(f"Error fetching venue {vid}: {e}")
            data = {}

        # Extract values (default empty if not present)
        venue_id = vid
        venue_name = data.get("ground", "")
        city = data.get("city", "")
        country = data.get("country", "")
        capacity = data.get("capacity", "")

        # Insert into MySQL with UPSERT
        cursor.execute("""
            INSERT INTO venues (venue_id, venue_name, city, country, capacity)
            VALUES (%s, %s, %s, %s, %s)
            ON DUPLICATE KEY UPDATE
                venue_name = VALUES(venue_name),
                city = VALUES(city),
                country = VALUES(country),
                capacity = VALUES(capacity)
        """, (venue_id, venue_name, city, country, capacity))

        count += 1

    conn.commit()
    print(f"{count} venue records inserted/updated.")


# Example usage
venue_ids = [41, 34, 27, 31, 81, 19, 10, 153, 50, 40, 80, 485, 87, 11]
extract_venue_details_insert(venue_ids)

14 venue records inserted/updated.

In [12]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS matches_with_scores(
    match_id BIGINT PRIMARY KEY,
    match_desc VARCHAR(255),
    team1 VARCHAR(255),
    team2 VARCHAR(255),
    start_date DATETIME,
    end_date DATETIME,
    status VARCHAR(255),
    state VARCHAR(255),
    venue VARCHAR(255),
    series_name VARCHAR(255),
    match_format VARCHAR(50),
    team1_score VARCHAR(50),
    team2_score VARCHAR(50)
)
""")

0

In [13]:
from datetime import datetime
import requests

def format_scores(team_score):
    if not team_score:
        return ""
    scores = []
    for key, innings in team_score.items():
        if innings:
            runs = innings.get("runs", 0)
            wickets = innings.get("wickets", 0)
            overs = innings.get("overs", 0)
            scores.append(f"{runs}/{wickets} ({overs} ov)")
    return " | ".join(scores)


# Extract match details from one series
def extract_series_matches_and_insert(data):
    match_details = data.get("matchDetails", [])

    count = 0

    for item in match_details:
        map_data = item.get("matchDetailsMap")
        if not map_data:
            continue

        matches = map_data.get("match", [])
        for m in matches:
            info = m.get("matchInfo", {})
            score = m.get("matchScore", {})

            team1_score = format_scores(score.get("team1Score"))
            team2_score = format_scores(score.get("team2Score"))

            start_dt = datetime.fromtimestamp(int(info.get("startDate", 0))/1000) if info.get("startDate") else None
            end_dt = datetime.fromtimestamp(int(info.get("endDate", 0))/1000) if info.get("endDate") else None

            match_id = info.get("matchId")
            match_desc = info.get("matchDesc")
            team1 = info.get("team1", {}).get("teamName")
            team2 = info.get("team2", {}).get("teamName")
            status = info.get("status")
            state = info.get("state")
            venue = info.get("venueInfo", {}).get("ground")
            series_name = info.get("seriesName")
            match_format = info.get("matchFormat")

            # Insert into DB
            cursor.execute("""
                INSERT INTO matches_with_scores (
                    match_id, match_desc, team1, team2, start_date, end_date,
                    status, state, venue, series_name, match_format,
                    team1_score, team2_score
                )
                VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
                ON DUPLICATE KEY UPDATE
                    match_desc=VALUES(match_desc),
                    team1=VALUES(team1),
                    team2=VALUES(team2),
                    start_date=VALUES(start_date),
                    end_date=VALUES(end_date),
                    status=VALUES(status),
                    state=VALUES(state),
                    venue=VALUES(venue),
                    series_name=VALUES(series_name),
                    match_format=VALUES(match_format),
                    team1_score=VALUES(team1_score),
                    team2_score=VALUES(team2_score)
            """, (
                match_id, match_desc, team1, team2, start_dt, end_dt,
                status, state, venue, series_name, match_format,
                team1_score, team2_score
            ))

            count += 1

    conn.commit()
    print(f"{count} match records inserted/updated.")
def fetch_api(url):
    headers = {
        "x-rapidapi-key": "07bd567654mshaf5d130ac122921p1c96cajsne9916179c774",
        "x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
    }
    response = requests.get(url, headers=headers)
    return response.json()

# Fetch multiple series and insert
series_ids = [8393, 4905, 8528, 3692]  

for sid in series_ids:
    url = f"https://cricbuzz-cricket.p.rapidapi.com/series/v1/{sid}"
    data = fetch_api(url)
    extract_series_matches_and_insert(data)

0 match records inserted/updated.
0 match records inserted/updated.
0 match records inserted/updated.
0 match records inserted/updated.

In [14]:
cursor.execute("""CREATE TABLE partnerships_data (
    id INT AUTO_INCREMENT PRIMARY KEY,
    match_id BIGINT NOT NULL,
    innings_no INT NOT NULL,
    batter1_id BIGINT NOT NULL,
    batter2_id BIGINT NOT NULL,
    batter1_name VARCHAR(100),
    batter2_name VARCHAR(100),
    runs_partnership INT,
    balls_faced INT,
    wicket_fallen INT,
    UNIQUE KEY uniq_partnership (match_id, innings_no, batter1_id, batter2_id, wicket_fallen)
)""")

OperationalError: (1050, "Table 'partnerships_data' already exists")

In [ ]:
import requests
import datetime


# --- API Headers ---
headers = {
    "x-rapidapi-key": "bb8592df63msh6e0b1fcf0b4efe6p19071ajsn35e95eba42a0",
    "x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

# --- Match IDs ---
match_ids = [121362, 123650, 59965, 48205, 122517]

count = 0
for mid in match_ids:
    url = f"https://cricbuzz-cricket.p.rapidapi.com/mcenter/v1/{mid}/hscard"
    response = requests.get(url, headers=headers)
    scorecard_data = response.json()

    score_cards = scorecard_data.get("scorecard", [])

    for innings in score_cards:
        innings_no = innings.get("inningsid", 0)

        # Partnerships list
        partnerships_list = innings.get("partnership", {}).get("partnership", [])

        for index, partnership_info in enumerate(partnerships_list):
            batter1_id = partnership_info.get("bat1id", 0)
            batter2_id = partnership_info.get("bat2id", 0)
            batter1_name = partnership_info.get("bat1name", "")
            batter2_name = partnership_info.get("bat2name", "")
            runs_partnership = partnership_info.get("totalruns", 0)
            balls_faced = partnership_info.get("totalballs", 0)

            # Wicket fallen = index + 1
            wicket_fallen = index + 1

            # Insert into MySQL
            cursor.execute("""
                INSERT INTO partnerships_data (
                    match_id, innings_no, batter1_id, batter2_id, batter1_name, batter2_name, 
                    runs_partnership, balls_faced, wicket_fallen
                ) VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s)
                ON DUPLICATE KEY UPDATE
                    runs_partnership=VALUES(runs_partnership),
                    balls_faced=VALUES(balls_faced),
                    wicket_fallen=VALUES(wicket_fallen)
            """, (mid, innings_no, batter1_id, batter2_id, batter1_name, batter2_name,
                  runs_partnership, balls_faced, wicket_fallen))

            count += 1

conn.commit()
print(f"Inserted/Updated {count} partnership records successfully.")

Inserted/Updated 52 partnership records successfully.

In [ ]:
cursor.execute(("""CREATE TABLE bowling (
    id INT AUTO_INCREMENT PRIMARY KEY,
    match_id BIGINT NOT NULL,
    innings_no INT NOT NULL,
    player_id BIGINT NOT NULL,
    player_name VARCHAR(100),
    overs FLOAT,
    runs_conceded INT,
    wickets INT,
    economy_rate FLOAT,
    venue VARCHAR(150),
    UNIQUE KEY uniq_bowling (match_id, innings_no, player_id)
)
"""))

0

In [ ]:
import requests
import mysql.connector



# --- API Headers ---
headers = {
    "x-rapidapi-key": "bb8592df63msh6e0b1fcf0b4efe6p19071ajsn35e95eba42a0",
    "x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

# --- Match IDs ---
match_ids = [100283, 38617, 38612, 38627, 75623, 78621, 48121, 70326, 91787, 60035, 100310, 75563]

count = 0
for mid in match_ids:
    try:
        # API URLs
        url_scorecard = f"https://cricbuzz-cricket.p.rapidapi.com/mcenter/v1/{mid}/hscard"
        url_match = f"https://cricbuzz-cricket.p.rapidapi.com/mcenter/v1/{mid}"

        scorecard_data = requests.get(url_scorecard, headers=headers).json()
        match_data = requests.get(url_match, headers=headers).json()

        if not scorecard_data or not match_data:
            continue

        # --- Venue ---
        venue_info = match_data.get("venueinfo", {})   # lowercase
        venue = f"{venue_info.get('ground', '')}, {venue_info.get('city', '')}".strip(', ')
        if not venue:
            venue = venue_info.get("ground", "") or venue_info.get("city", "")

        # --- Match ID ---
        match_id = match_data.get("matchid", mid)

        # --- Scorecard ---
        score_cards = scorecard_data.get("scorecard", [])

        for innings in score_cards:
            innings_no = innings.get("inningsid", 0)
            bowlers_list = innings.get("bowler", [])

            for bowler_info in bowlers_list:
                player_id = bowler_info.get("id", 0)
                player_name = bowler_info.get("name", "")
                overs = float(bowler_info.get("overs", 0))
                runs_conceded = int(bowler_info.get("runs", 0))
                wickets = int(bowler_info.get("wickets", 0))
                economy_rate = float(bowler_info.get("economy", 0))

                # Insert into MySQL
                cursor.execute("""
                    INSERT INTO bowling (
                        match_id, innings_no, player_id, player_name, overs, runs_conceded, wickets, economy_rate, venue
                    ) VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s)
                    ON DUPLICATE KEY UPDATE
                        overs=VALUES(overs),
                        runs_conceded=VALUES(runs_conceded),
                        wickets=VALUES(wickets),
                        economy_rate=VALUES(economy_rate),
                        venue=VALUES(venue)
                """, (match_id, innings_no, player_id, player_name, overs, runs_conceded, wickets, economy_rate, venue))

                count += 1

    except Exception as e:
        print(f"Failed to fetch bowling data for match {mid}: {e}")

conn.commit()
print(f"Inserted/Updated {count} bowling innings records successfully.")

Inserted/Updated 174 bowling innings records successfully.

In [ ]:
cursor.execute("""CREATE TABLE batting (
    id INT AUTO_INCREMENT PRIMARY KEY,
    match_id BIGINT NOT NULL,
    innings_no INT NOT NULL,
    player_id BIGINT NOT NULL,
    player_name VARCHAR(100),
    runs INT,
    balls_faced INT,
    strike_rate FLOAT,
    match_date DATE,
    UNIQUE KEY uniq_batting (match_id, innings_no, player_id)
)
 """)

0

In [ ]:
import requests

from datetime import datetime


# --- API Headers ---
headers = {
    "x-rapidapi-key": "bb8592df63msh6e0b1fcf0b4efe6p19071ajsn35e95eba42a0 ",
    "x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

# --- Match IDs ---
match_ids = [
    75476, 100283, 100290, 130019, 82462, 116981, 116990, 
    76465, 105804, 87626, 87878, 116972, 69862, 43061, 
    76535, 100312, 100321, 112462, 60035, 78558, 60042, 
    100328, 75476, 59979, 59981, 30554, 32047, 77894, 
    91778, 91787, 105780, 105770, 105762
]

count = 0
for mid in match_ids:
    try:
        url = f"https://cricbuzz-cricket.p.rapidapi.com/mcenter/v1/{mid}/hscard"
        response = requests.get(url, headers=headers)
        data = response.json()

        if not data:
            continue

        # --- Match Date ---
        match_date = None
        match_date_ms = data.get("responselastupdated")
        if match_date_ms:
            match_date = datetime.fromtimestamp(int(match_date_ms) / 1000).date()

        # --- Innings ---
        for innings in data.get("scorecard", []):
            innings_no = innings.get("inningsid")
            batsmen_list = innings.get("batsman", [])

            for batsman in batsmen_list:
                player_id = batsman.get("id")
                player_name = batsman.get("name")
                runs = int(batsman.get("runs", 0))
                balls_faced = int(batsman.get("balls", 0))
                strike_rate = float(batsman.get("strkrate", 0))

                # Insert into MySQL
                cursor.execute("""
                    INSERT INTO batting_innings (
                        match_id, innings_no, player_id, player_name, runs, balls_faced, strike_rate, match_date
                    ) VALUES (%s,%s,%s,%s,%s,%s,%s,%s)
                    ON DUPLICATE KEY UPDATE
                        runs=VALUES(runs),
                        balls_faced=VALUES(balls_faced),
                        strike_rate=VALUES(strike_rate),
                        match_date=VALUES(match_date)
                """, (mid, innings_no, player_id, player_name, runs, balls_faced, strike_rate, match_date))

                count += 1

    except Exception as e:
        print(f"Failed to fetch batting data for match {mid}: {e}")

conn.commit()
print(f"Inserted/Updated {count} batting records successfully.")

In [ ]:
cursor.execute("""CREATE TABLE fielding (
    id INT AUTO_INCREMENT PRIMARY KEY,
    match_id BIGINT NOT NULL,
    player_id BIGINT NOT NULL,
    player_name VARCHAR(100),
    catches INT DEFAULT 0,
    stumpings INT DEFAULT 0,
    UNIQUE KEY uniq_fielding (match_id, player_id)
) """)

0

In [ ]:
import requests
import mysql.connector

# --- API Headers ---
headers = {
    "x-rapidapi-key": "bb8592df63msh6e0b1fcf0b4efe6p19071ajsn35e95eba42a0",
    "x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

# --- Match IDs ---
match_ids = [
    122517, 100283, 100290, 130019, 82462, 116981, 116990, 
    76465, 105804, 87626, 87878, 116972, 69862, 43061, 
    76535, 100312, 60042, 105770,
    100328, 77894, 
    91778, 91787, 105780, 105770, 113864
    
]

count = 0
for mid in match_ids:
    try:
        url_scorecard = f"https://cricbuzz-cricket.p.rapidapi.com/mcenter/v1/{mid}/hscard"
        scorecard_data = requests.get(url_scorecard, headers=headers).json()

        if not scorecard_data:
            continue

        # --- Player name → ID mapping ---
        player_name_to_id = {}
        score_cards = scorecard_data.get("scorecard", [])

        for innings in score_cards:
            for player_info in innings.get("batsman", []) + innings.get("bowler", []):
                name = player_info.get("name")
                if name:
                    player_name_to_id[name.strip()] = player_info.get("id")

        # --- Extract fielding stats ---
        fielding_stats = {}
        for innings in score_cards:
            batsmen_list = innings.get("batsman", [])
            for bat_info in batsmen_list:
                out_desc = bat_info.get("outdec", "").strip()

                # --- Catch detection ---
                if out_desc.startswith("c "):
                    # Example: "c Kohli b Anderson"
                    parts = out_desc.split(" b ")
                    if len(parts) >= 2:
                        fielder = parts[0].replace("c", "").strip()
                        if fielder:
                            if fielder not in fielding_stats:
                                fielding_stats[fielder] = {"catches": 0, "stumpings": 0}
                            fielding_stats[fielder]["catches"] += 1

                # --- Stumping detection ---
                elif out_desc.startswith("st "):
                    # Example: "st Dhoni b Murali"
                    parts = out_desc.split(" b ")
                    if len(parts) >= 2:
                        keeper = parts[0].replace("st", "").strip()
                        if keeper:
                            if keeper not in fielding_stats:
                                fielding_stats[keeper] = {"catches": 0, "stumpings": 0}
                            fielding_stats[keeper]["stumpings"] += 1

        # --- Insert into DB ---
        for player_name, stats in fielding_stats.items():
            player_id = player_name_to_id.get(player_name, None)
            if player_id and (stats["catches"] > 0 or stats["stumpings"] > 0):
                cursor.execute("""
                    INSERT INTO fielding (
                        match_id, player_id, player_name, catches, stumpings
                    ) VALUES (%s,%s,%s,%s,%s)
                    ON DUPLICATE KEY UPDATE
                        catches=VALUES(catches),
                        stumpings=VALUES(stumpings)
                """, (mid, player_id, player_name, stats["catches"], stats["stumpings"]))
                count += 1

    except Exception as e:
        print(f"Failed to fetch fielding data for match {mid}: {e}")

conn.commit()
print(f"Inserted/Updated {count} fielding records successfully.")

Inserted/Updated 169 fielding records successfully.

In [ ]:
cursor.execute("""CREATE TABLE bowlers_data (
    id INT AUTO_INCREMENT PRIMARY KEY,
    match_id BIGINT NOT NULL,
    player_id BIGINT NOT NULL,
    player_name VARCHAR(100),
    team VARCHAR(100),
    overs FLOAT,
    maidens INT,
    runs_conceded INT,
    wickets INT,
    economy_rate FLOAT,
    UNIQUE KEY uniq_bowling (match_id, player_id)

)
""")

0

In [ ]:
import requests




# --- API Headers ---
headers = {
    "x-rapidapi-key": "bb8592df63msh6e0b1fcf0b4efe6p19071ajsn35e95eba42a0",
    "x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

# --- Match IDs ---
match_ids = [122517, 100283, 100290, 130019, 82462, 116981, 116990, 
    76465, 105804, 87626, 87878, 116972, 69862, 43061, 
    76535, 100312, 60042, 105770,
    100328, 77894, 
    91778, 91787, 105780, 105770, 113864
    
]

count = 0
for mid in match_ids:
    try:
        url_scorecard = f"https://cricbuzz-cricket.p.rapidapi.com/mcenter/v1/{mid}/hscard"
        scorecard_data = requests.get(url_scorecard, headers=headers).json()

        if not scorecard_data:
            continue

        score_cards = scorecard_data.get("scorecard", [])

        # --- Extract Bowling Stats ---
        for innings in score_cards:
            team_name = innings.get("batteamname")  # batting side name
            bowlers = innings.get("bowler", [])

            for bowler in bowlers:
                player_id = bowler.get("id")
                player_name = bowler.get("name")

                if not player_id or not player_name:
                    continue

                overs = float(bowler.get("overs", 0))
                maidens = int(bowler.get("maidens", 0))
                runs_conceded = int(bowler.get("runs", 0))
                wickets = int(bowler.get("wickets", 0))
                economy = float(bowler.get("economy", 0))

                # --- Insert into DB ---
                cursor.execute("""
                    INSERT INTO bowlers_data (
                        match_id, player_id, player_name, team,
                        overs, maidens, runs_conceded, wickets, economy_rate
                    ) VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s)
                    ON DUPLICATE KEY UPDATE
                        overs=VALUES(overs),
                        maidens=VALUES(maidens),
                        runs_conceded=VALUES(runs_conceded),
                        wickets=VALUES(wickets),
                        economy_rate=VALUES(economy_rate)
                """, (mid, player_id, player_name, team_name,
                      overs, maidens, runs_conceded, wickets, economy))
                count += 1

    except Exception as e:
        print(f"Failed to fetch bowling data for match {mid}: {e}")

conn.commit()
print(f"✅ Inserted/Updated {count} bowling records successfully.")

✅ Inserted/Updated 334 bowling records successfully.

In [ ]:
cursor.execute(("""CREATE TABLE batsmen_data (
    id INT AUTO_INCREMENT PRIMARY KEY,
    match_id BIGINT NOT NULL,
    innings_no INT NOT NULL,
    team VARCHAR(100),
    player_id BIGINT NOT NULL,
    player_name VARCHAR(100),
    runs INT,
    balls_faced INT,
    fours INT,
    sixes INT,
    strike_rate FLOAT,
    dismissal VARCHAR(255),
    UNIQUE KEY uniq_batting (match_id, innings_no, player_id)
)
 """))

0

In [ ]:
import requests


# --- API Headers ---
headers = {
    "x-rapidapi-key": "bb8592df63msh6e0b1fcf0b4efe6p19071ajsn35e95eba42a0",
    "x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

# --- Match IDs ---
match_ids = [
   122517, 100283, 100290, 130019, 82462, 116981, 116990, 
    76465, 105804, 87626, 87878, 116972, 69862, 43061, 
    76535, 100312, 60042, 105770,
    100328, 77894, 
    91778, 91787, 105780, 105770, 113864
]

count = 0
for mid in match_ids:
    try:
        url_scorecard = f"https://cricbuzz-cricket.p.rapidapi.com/mcenter/v1/{mid}/hscard"
        scorecard_data = requests.get(url_scorecard, headers=headers).json()

        if not scorecard_data:
            continue

        score_cards = scorecard_data.get("scorecard", [])

        # --- Extract Batting Stats ---
        for innings in score_cards:
            team_name = innings.get("batteamname")
            innings_no = innings.get("inningsid")
            batsmen = innings.get("batsman", [])

            for bat in batsmen:
                player_id = bat.get("id")
                player_name = bat.get("name")

                if not player_id or not player_name:
                    continue

                runs = int(bat.get("runs", 0))
                balls = int(bat.get("balls", 0))
                fours = int(bat.get("fours", 0))
                sixes = int(bat.get("sixes", 0))
                strike_rate = float(bat.get("strkrate", 0))
                dismissal = bat.get("outdec")

                # --- Insert into DB ---
                cursor.execute("""
                    INSERT INTO batsmen_data (
                        match_id, innings_no, team, player_id, player_name,
                        runs, balls_faced, fours, sixes, strike_rate, dismissal
                    ) VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
                    ON DUPLICATE KEY UPDATE
                        runs=VALUES(runs),
                        balls_faced=VALUES(balls_faced),
                        fours=VALUES(fours),
                        sixes=VALUES(sixes),
                        strike_rate=VALUES(strike_rate),
                        dismissal=VALUES(dismissal)
                """, (mid, innings_no, team_name, player_id, player_name,
                      runs, balls, fours, sixes, strike_rate, dismissal))
                count += 1

    except Exception as e:
        print(f"Failed to fetch batting data for match {mid}: {e}")

conn.commit()
print(f"✅ Inserted/Updated {count} batting records successfully.")

✅ Inserted/Updated 660 batting records successfully.

In [ ]:
cursor.execute("""CREATE TABLE IF NOT EXISTS player_stats (
    player_id INT PRIMARY KEY,
    player_name VARCHAR(100),
    role VARCHAR(50),
    test_runs INT,
    odi_runs INT,
    t20_runs INT
)""")

0

In [ ]:
import requests




# --- API Headers ---
headers = {
    "x-rapidapi-key": "42ba173510msh8668786dd4440a9p1855c7jsnb61dc18d9c24",
    "x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

# --- Player IDs ---
player_ids = [576, 69, 265, 247, 413, 8019, 6326,1413,65]  # Example

count = 0
for pid in player_ids:
    try:
        # --- Player Profile ---
        url_profile = f"https://cricbuzz-cricket.p.rapidapi.com/stats/v1/player/{pid}"
        profile_data = requests.get(url_profile, headers=headers).json()

        if not profile_data:
            continue

        player_name = profile_data.get("name")
        role = profile_data.get("role")

        # --- Batting Stats ---
        url_batting = f"https://cricbuzz-cricket.p.rapidapi.com/stats/v1/player/{pid}/batting"
        batting_data = requests.get(url_batting, headers=headers).json()

        # Defaults
        test_runs = odi_runs = t20_runs = 0

        values = batting_data.get("values", [])
        for item in values:
            row = item.get("values", [])
            if row and row[0] == "Runs":
                test_runs = int(row[1]) if row[1].isdigit() else 0
                odi_runs = int(row[2]) if row[2].isdigit() else 0
                t20_runs = int(row[3]) if row[3].isdigit() else 0

        # --- Insert into DB ---
        cursor.execute("""
            INSERT INTO player_stats (
                player_id, player_name, role, test_runs, odi_runs, t20_runs
            ) VALUES (%s,%s,%s,%s,%s,%s)
            ON DUPLICATE KEY UPDATE
                player_name=VALUES(player_name),
                role=VALUES(role),
                test_runs=VALUES(test_runs),
                odi_runs=VALUES(odi_runs),
                t20_runs=VALUES(t20_runs)
        """, (pid, player_name, role, test_runs, odi_runs, t20_runs))
        count += 1

    except Exception as e:
        print(f"Failed to fetch player {pid}: {e}")

conn.commit()
print(f"✅ Inserted/Updated {count} player records successfully.")

✅ Inserted/Updated 9 player records successfully.

In [ ]:
cursor.execute("""CREATE TABLE IF NOT EXISTS end_to_end_match_info (
    match_id BIGINT PRIMARY KEY,
    format VARCHAR(20),
    series_name VARCHAR(200),
    match_date DATE,
    venue VARCHAR(150),
    team1 VARCHAR(100),
    team2 VARCHAR(100),
    toss_winner VARCHAR(100),
    toss_decision VARCHAR(20),
    match_winner VARCHAR(100),
    win_margin VARCHAR(200)
)
  """)

0

In [ ]:
import requests
from datetime import datetime

# --- API Headers ---
headers = {
    "x-rapidapi-key": "bb8592df63msh6e0b1fcf0b4efe6p19071ajsn35e95eba42a0",
    "x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

# --- Match IDs ---
match_ids = [
    
   122517, 100283, 100290, 130019, 82462, 116981, 116990, 
    76465, 105804, 87626, 87878, 116972, 69862, 43061, 
    76535, 100312, 60042, 105770,
    100328, 77894, 
    91778, 91787, 105780, 105770, 113864
    
]

count = 0
for mid in match_ids:
    try:
        # --- API URLs ---
        url_match = f"https://cricbuzz-cricket.p.rapidapi.com/mcenter/v1/{mid}"
        url_leanback = f"https://cricbuzz-cricket.p.rapidapi.com/mcenter/v1/{mid}/leanback"

        match_data = requests.get(url_match, headers=headers).json()
        leanback_data = requests.get(url_leanback, headers=headers).json()

        if not match_data:
            continue

        # --- Extract fields ---
        match_id = match_data.get("matchid")
        series_name = match_data.get("seriesname")
        match_format = match_data.get("matchformat")
        match_date = datetime.fromtimestamp(match_data.get("startdate", 0)/1000).date() if match_data.get("startdate") else None
        venue = match_data.get("venueinfo", {}).get("ground")
        team1 = match_data.get("team1", {}).get("teamname")
        team2 = match_data.get("team2", {}).get("teamname")

        toss_info = leanback_data.get("matchheaders", {}).get("tossresults", {})
        toss_winner = toss_info.get("tosswinnername")
        toss_decision = toss_info.get("decision")

        matchheaders = leanback_data.get("matchheaders", {})
        match_winner = None
        if matchheaders.get("status"):
            match_winner = matchheaders["status"].split(" won")[0]

        win_margin = matchheaders.get("status")

        # --- Insert into DB ---
        cursor.execute("""
            INSERT INTO end_to_end_match_info (
                match_id, format, series_name, match_date, venue,
                team1, team2, toss_winner, toss_decision, match_winner, win_margin
            ) VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
            ON DUPLICATE KEY UPDATE
                format=VALUES(format),
                series_name=VALUES(series_name),
                match_date=VALUES(match_date),
                venue=VALUES(venue),
                team1=VALUES(team1),
                team2=VALUES(team2),
                toss_winner=VALUES(toss_winner),
                toss_decision=VALUES(toss_decision),
                match_winner=VALUES(match_winner),
                win_margin=VALUES(win_margin)
        """, (match_id, match_format, series_name, match_date, venue,
              team1, team2, toss_winner, toss_decision, match_winner, win_margin))
        count += 1

    except Exception as e:
        print(f"❌ Failed to fetch match {mid}: {e}")

conn.commit()
print(f"✅ Inserted/Updated {count} match records successfully.")

✅ Inserted/Updated 25 match records successfully.

In [ ]:
cursor.execute("""CREATE TABLE players_info (
    player_id INT PRIMARY KEY,
    full_name VARCHAR(100),
    short_name VARCHAR(100),
    country VARCHAR(50),
    role VARCHAR(50),
    batting_style VARCHAR(50),
    bowling_style VARCHAR(50),
    total_runs INT,
    total_wickets INT
)
 """)

0

In [ ]:
import requests
import mysql.connector

# --- API Fetch Helper ---
def fetch_api(url):
    headers = {
        "x-rapidapi-key": "fa8e2f141fmsh93e60c107630b1ep15131djsnd985ef01f9ec",  
        "x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
    }
    response = requests.get(url, headers=headers)
    return response.json()

# --- Extract stat for one format ---
def extract_stat(data, stat_name, format_type):
    headers = data.get("headers", [])
    values_list = data.get("values", [])
    
    if format_type not in headers:
        return 0
    
    col_index = headers.index(format_type)
    
    for item in values_list:
        row = item.get("values", [])
        if row and row[0].lower() == stat_name.lower():
            value = row[col_index]
            try:
                return int(value)
            except (ValueError, TypeError):
                return 0
    return 0

# --- Sum stats across formats ---
def sum_stats_across_formats(data, stat_name):
    formats = ["Test", "ODI", "T20"]
    total = 0
    for fmt in formats:
        total += extract_stat(data, stat_name, fmt)
    return total

# --- Player Data Fetch + DB Insert ---
def fetch_and_insert_players(player_ids):
    count = 0
    for pid in player_ids:
        try:
            # Fetch profile
            profile = fetch_api(f"https://cricbuzz-cricket.p.rapidapi.com/stats/v1/player/{pid}")
            batting = fetch_api(f"https://cricbuzz-cricket.p.rapidapi.com/stats/v1/player/{pid}/batting")
            bowling = fetch_api(f"https://cricbuzz-cricket.p.rapidapi.com/stats/v1/player/{pid}/bowling")
            
            # Extract fields
            player_id = pid
            full_name = profile.get("name")
            short_name = profile.get("nickName")
            country = profile.get("intlTeam")
            role = profile.get("role")
            batting_style = profile.get("bat")
            bowling_style = profile.get("bowl")
            total_runs = sum_stats_across_formats(batting, "Runs")
            total_wickets = sum_stats_across_formats(bowling, "Wickets")
            
            # --- Insert into DB ---
            cursor.execute("""
                INSERT INTO players_info (
                    player_id, full_name, short_name, country, role,
                    batting_style, bowling_style, total_runs, total_wickets
                ) VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s)
                ON DUPLICATE KEY UPDATE
                    full_name=VALUES(full_name),
                    short_name=VALUES(short_name),
                    country=VALUES(country),
                    role=VALUES(role),
                    batting_style=VALUES(batting_style),
                    bowling_style=VALUES(bowling_style),
                    total_runs=VALUES(total_runs),
                    total_wickets=VALUES(total_wickets)
            """, (player_id, full_name, short_name, country, role,
                  batting_style, bowling_style, total_runs, total_wickets))
            
            count += 1
            print(f"✅ Inserted/Updated player {pid}: {full_name}")
        except Exception as e:
            print(f"❌ Failed to fetch player {pid}: {e}")
    
    conn.commit()
    print(f"🎯 Inserted/Updated {count} players successfully.")

# --- Example Player IDs ---
player_ids = [576, 11813,265,9647, 1413, 11808, 8733,14504,413,587,8019,6326,20538,370,7825]
fetch_and_insert_players(player_ids)

✅ Inserted/Updated player 576: Rohit Sharma
✅ Inserted/Updated player 11813: Ruturaj Gaikwad
✅ Inserted/Updated player 265: MS Dhoni
✅ Inserted/Updated player 9647: Hardik Pandya
✅ Inserted/Updated player 1413: Virat Kohli
✅ Inserted/Updated player 11808: Shubman Gill
✅ Inserted/Updated player 8733: KL Rahul
✅ Inserted/Updated player 14504: Tilak Varma
✅ Inserted/Updated player 413: Suresh Raina
✅ Inserted/Updated player 587: Ravindra Jadeja
✅ Inserted/Updated player 8019: Joe Root
✅ Inserted/Updated player 6326: Kane Williamson
✅ Inserted/Updated player 20538: Dewald Brevis
✅ Inserted/Updated player 370: AB de Villiers
✅ Inserted/Updated player 7825: Faf du Plessis
🎯 Inserted/Updated 15 players successfully.

In [ ]:
cursor.execute("""CREATE TABLE top_odi_runs (
    player_id INT PRIMARY KEY,       
    player_name VARCHAR(100),        
    matches INT,                     
    innings INT,                     
    runs INT,                        
    average FLOAT                    
)
""")

0

In [ ]:
import requests
import mysql.connector
import pandas as pd



# --- Fetch Top ODI Runs ---
def fetch_top_odi_runs(api_key):
    url = "https://cricbuzz-cricket.p.rapidapi.com/stats/v1/topstats/0"
    querystring = {"statsType": "mostRuns", "matchType": "2"}  # "2" = ODI
    
    headers = {
        "x-rapidapi-key": api_key,
        "x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
    }
    
    response = requests.get(url, headers=headers, params=querystring)
    
    if response.status_code != 200:
        raise Exception(f"API request failed with status code {response.status_code}")
    
    data = response.json()
    
    rows = []
    values = data.get("values", [])
    
    for item in values:
        row = item.get("values", [])
        if len(row) >= 6:
            try:
                rows.append({
                    "player_id": int(row[0]),
                    "player_name": row[1],
                    "matches": int(row[2]),
                    "innings": int(row[3]),
                    "runs": int(row[4]),
                    "average": float(row[5])
                })
            except ValueError:
                continue
    
    return rows

# --- Insert into DB ---
def insert_top_odi_runs(rows):
    count = 0
    for player in rows:
        try:
            cursor.execute("""
                INSERT INTO top_odi_runs (
                    player_id, player_name, matches, innings, runs, average
                ) VALUES (%s,%s,%s,%s,%s,%s)
                ON DUPLICATE KEY UPDATE
                    player_name=VALUES(player_name),
                    matches=VALUES(matches),
                    innings=VALUES(innings),
                    runs=VALUES(runs),
                    average=VALUES(average)
            """, (
                player["player_id"], player["player_name"], 
                player["matches"], player["innings"], 
                player["runs"], player["average"]
            ))
            count += 1
        except Exception as e:
            print(f"❌ Error inserting {player['player_name']}: {e}")
    
    conn.commit()
    print(f"✅ Inserted/Updated {count} ODI top run records successfully.")

# --- RUN ---
api_key = "fa8e2f141fmsh93e60c107630b1ep15131djsnd985ef01f9ec" 
top_odi_rows = fetch_top_odi_runs(api_key)
insert_top_odi_runs(top_odi_rows)

✅ Inserted/Updated 20 ODI top run records successfully.

In [ ]:
cursor.execute("""CREATE TABLE sample (
    id INT AUTO_INCREMENT PRIMARY KEY,
    match_id BIGINT NOT NULL,
    innings_no INT NOT NULL,
    player_id BIGINT NOT NULL,
    player_name VARCHAR(100),
    runs INT,
    balls_faced INT,
    strike_rate FLOAT,
    match_date DATE,
    UNIQUE KEY uniq_batting (match_id, innings_no, player_id)
)
 """)

0

In [ ]:
import requests
import mysql.connector
from datetime import datetime


# --- API Headers ---
headers = {
    "x-rapidapi-key": "fa8e2f141fmsh93e60c107630b1ep15131djsnd985ef01f9ec",
    "x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

# --- Match IDs ---
match_ids = [
    122517, 100283, 100290, 130019, 82462, 116981, 116990, 
    76465, 105804, 87626, 87878, 116972, 69862, 43061, 
    76535, 100312, 60042, 105770,
    100328, 77894, 
    91778, 91787, 105780, 105770, 113864
]

count = 0
for mid in match_ids:
    try:
        url = f"https://cricbuzz-cricket.p.rapidapi.com/mcenter/v1/{mid}/hscard"
        response = requests.get(url, headers=headers)
        data = response.json()

        if not data:
            continue

        # --- Match Date ---
        #match_date = None
        # --- Match Date ---
        match_date = None
        match_header = data.get("matchHeader", {})
        start_time = match_header.get("startTime")   # correct field for match date

        if start_time:
            match_date = datetime.fromtimestamp(int(start_time) / 1000).date()

        # match_date_ms = data.get("responselastupdated")
        # if match_date_ms:
        #     match_date = datetime.datetime.fromtimestamp(int(match_date_ms) / 1000).date()

        # --- Innings ---
        for innings in data.get("scorecard", []):
            innings_no = innings.get("inningsid")
            batsmen_list = innings.get("batsman", [])

            for batsman in batsmen_list:
                player_id = batsman.get("id")
                player_name = batsman.get("name")
                runs = int(batsman.get("runs", 0))
                balls_faced = int(batsman.get("balls", 0))
                strike_rate = float(batsman.get("strkrate", 0))

                # Insert into MySQL
                cursor.execute("""
                    INSERT INTO sample (
                        match_id, innings_no, player_id, player_name, runs, balls_faced, strike_rate, match_date
                    ) VALUES (%s,%s,%s,%s,%s,%s,%s,%s)
                    ON DUPLICATE KEY UPDATE
                        runs=VALUES(runs),
                        balls_faced=VALUES(balls_faced),
                        strike_rate=VALUES(strike_rate),
                        match_date=VALUES(match_date)
                """, (mid, innings_no, player_id, player_name, runs, balls_faced, strike_rate, match_date))

                count += 1

    except Exception as e:
        print(f"Failed to fetch batting data for match {mid}: {e}")

conn.commit()
print(f"Inserted/Updated {count} batting records successfully.")

Inserted/Updated 671 batting records successfully.

In [19]:
cursor.execute("""create table if not exists matches_recent_1(
match_id INT PRIMARY KEY,
    series_id INT,
    series_name VARCHAR(255),
    match_desc VARCHAR(255),
    match_format VARCHAR(50),
    start_date DATETIME,
    state VARCHAR(100),
    status VARCHAR(255),
    team1 VARCHAR(100),
    team2 VARCHAR(100),
    venue VARCHAR(255),
    city VARCHAR(100))""")

0

In [23]:
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/matches/v1/recent"

headers = {
	"x-rapidapi-key": "fa8e2f141fmsh93e60c107630b1ep15131djsnd985ef01f9ec",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

data_3 = response.json()

data_3

#insertion


count = 0
for match_type in data_3.get("typeMatches", []):
    for series in match_type.get("seriesMatches", []):
        series_data = series.get("seriesAdWrapper", {})
        series_id = series_data.get("seriesId")
        series_name = series_data.get("seriesName")

        for match in series_data.get("matches", []):
            info = match.get("matchInfo", {})
            match_id = info.get("matchId")
            match_desc = info.get("matchDesc")
            match_format = info.get("matchFormat")
            start_date = info.get("startDate")
            state = info.get("state")
            status = info.get("status")
            team1 = info.get("team1", {}).get("teamName")
            team2 = info.get("team2", {}).get("teamName")
            venue = info.get("venueInfo", {}).get("ground")
            city = info.get("venueInfo", {}).get("city")

            start_date = datetime.fromtimestamp(int(start_date) / 1000) if start_date else None

            # Insert into MySQL
            cursor.execute("""
                INSERT INTO matches_recent_1(match_id, series_id, series_name, match_desc, match_format, start_date,state,status, team1, team2, venue, city)
                VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
                ON DUPLICATE KEY UPDATE
                series_id=VALUES(series_id),
                series_name=VALUES(series_name),
                match_desc=VALUES(match_desc),
                match_format=VALUES(match_format),
                start_date=VALUES(start_date),
                state = VALUES(state),
                status=VALUES(status),
                team1=VALUES(team1),
                team2=VALUES(team2),
                venue=VALUES(venue),
                city=VALUES(city)
            """, (match_id, series_id, series_name, match_desc, match_format, start_date,state, status, team1, team2, venue, city))

            count += 1

conn.commit()
print(f"{count} recent match records inserted/updated.")

53 recent match records inserted/updated.

In [27]:
cursor.execute("""CREATE TABLE batting_1(
    id INT AUTO_INCREMENT PRIMARY KEY,
    match_id BIGINT NOT NULL,
    innings_no INT NOT NULL,
    player_id BIGINT NOT NULL,
    player_name VARCHAR(100),
    runs INT,
    balls_faced INT,
    strike_rate FLOAT,
    match_date DATE,
    UNIQUE KEY uniq_batting (match_id, innings_no, player_id)
)
 """)

0

In [ ]:
import requests

from datetime import datetime


# --- API Headers ---
headers = {
    "x-rapidapi-key": "fa8e2f141fmsh93e60c107630b1ep15131djsnd985ef01f9ec",
    "x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

# --- Match IDs ---
match_ids = [
    122517, 100283, 100290, 130019, 82462, 116981, 116990, 
    76465, 105804, 87626, 87878, 116972, 69862, 43061, 
    76535, 100312, 60042, 105770,
    100328, 77894, 
    91778, 91787, 105780, 105770, 113864
]

count = 0
for mid in match_ids:
    try:
        url = f"https://cricbuzz-cricket.p.rapidapi.com/mcenter/v1/{mid}/hscard"
        response = requests.get(url, headers=headers)
        data = response.json()

        if not data:
            continue

        # --- Match Date (Correct field: matchHeader.startTime) ---
        match_date = None
        if "matchHeader" in data and "startTime" in data["matchHeader"]:
            match_date = datetime.fromtimestamp(int(data["matchHeader"]["startTime"]) / 1000)
        # --- Innings ---
        for innings in data.get("scorecard", []):
            innings_no = innings.get("inningsId") or innings.get("inningsid")
            batsmen_list = innings.get("batsman", [])

            for batsman in batsmen_list:
                player_id = batsman.get("id")
                player_name = batsman.get("name")
                runs = int(batsman.get("runs", 0))
                balls_faced = int(batsman.get("balls", 0))
                strike_rate = float(batsman.get("strkRate", batsman.get("strkrate", 0)))
                

                # --- Insert into MySQL ---
                cursor.execute("""
                    INSERT INTO batting_1 (
                        match_id, innings_no, player_id, player_name, runs, balls_faced, strike_rate, match_date
                    ) VALUES (%s,%s,%s,%s,%s,%s,%s,%s)
                    ON DUPLICATE KEY UPDATE
                        runs=VALUES(runs),
                        balls_faced=VALUES(balls_faced),
                        strike_rate=VALUES(strike_rate),
                        match_date=VALUES(match_date)
                """, (mid, innings_no, player_id, player_name, runs, balls_faced, strike_rate, match_date))

                count += 1

    except Exception as e:
        print(f"Failed to fetch batting data for match {mid}: {e}")

conn.commit()
print(f"Inserted/Updated {count} batting records successfully.")

Inserted/Updated 0 batting records successfully.